# Implementing Deep Learning Models with Pytorch

## Introduction to Pytorch


Pytorch is described as:


A Python-based scientific computing package targeted at two sets of audiences:

1. A replacement for NumPy to use the power of GPUs
2. A deep learning research platform that provides maximum flexibility and speed



In [2]:
#!pip install torch

In [3]:
import torch

## Tensors

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.1020e-38],
        [5.2348e-39, 5.9694e-39, 8.9082e-39],
        [1.0194e-38, 9.1837e-39, 4.6837e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2021, 0.7989, 0.7000],
        [0.7207, 0.6235, 0.0695],
        [0.6087, 0.3331, 0.3649],
        [0.6331, 0.5589, 0.6533],
        [0.4001, 0.1888, 0.1199]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
print(x.size())

torch.Size([2])


In [9]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [10]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [11]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [12]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!